ol:
  service:
    messaging:
      events-exchange: ${OL_EVENTS_EXCHANGE:ol.exchange.events}
      commands-exchange: ${OL_EVENTS_EXCHANGE:ol.exchange.commands}
      coverage: ${OL_MESSAGE_COVERAGE:false}
      registry:
        enabled: ${OL_SCHEMA_REGISTRY_ENABLED:false}
        url: ${OL_SCHEMA_REGISTRY_URL:http://localhost:8990}
        format: ${OL_SCHEMA_FORMAT:avro}
      outbox:
        dispatcher:
          fixedDelay: 1000
          enabled: true
          wakeupAfterCommit: true
        maxAttempts: 10
        confirmTimeoutMillis: 5000
      metrics:
        queues:
          main: ${ACC_METRICS_MAIN_QUEUE:}
          dlq: ${ACC_METRICS_DLQ_QUEUE:}
      retry:
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2.0
        max-interval: 10000
